<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H2NQ5S1" ignored="0" name="Nopackage" tests="5" failures="2" timestamp="2020-11-11T08:11:27 CST" time="7.752" errors="0">
  <testcase name="test1" time="0.006" classname="com.webtest.demo.TestDemo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.TestDemo.test1(TestDemo.java:15)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="com.webtest.demo.TestDemo"/>
  <testcase name="test3" time="0.001" classname="com.webtest.demo.TestDemo"/>
  <testcase name="test4" time="0.0" classname="com.webtest.demo.TestDemo">
    <failure type="java.lang.AssertionError" message="expected [5] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [1]
at com.webtest.demo.TestDemo.test4(TestDemo.java:30)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.0" classname="com.webtest.demo.TestDemo"/>
</testsuite> <!-- Nopackage -->
